<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hcr3a</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="olmer@gmail.com">ros-industrial</maintainer>
  <license>TODO: License declaration</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  
        <depend>urdf</depend>
      <build_depend>launch_ros</build_depend>
      <exec_depend>launch_ros</exec_depend>
      <exec_depend>robot_state_publisher</exec_depend>
      <exec_depend>joint_state_publisher_gui</exec_depend>
      <exec_depend>realsense2_description</exec_depend>
      <exec_depend>realsense2_camera</exec_depend>
      <exec_depend>gripper_controllers</exec_depend>
      <exec_depend>octomap_rviz_plugins</exec_depend>
      <exec_depend>octomap_ros</exec_depend>
      <exec_depend>octomap</exec_depend>
      <exec_depend>moveit_visual_tools</exec_depend>
      <exec_depend>moveit_ros_perception</exec_depend>
      <exec_depend>moveit_ros_occupancy_map_monitor</exec_depend>
      <exec_depend>moveit_ros_planning</exec_depend>
      <exec_depend>moveit_planners</exec_depend>
      <exec_depend>chomp_motion_planner</exec_depend>
      <exec_depend>ompl</exec_depend>
      <exec_depend>stomp</exec_depend>
      <exec_depend>pilz_industrial_motion_planner</exec_depend>
      <exec_depend>moveit_planners_chomp</exec_depend>
      <exec_depend>moveit_planners_ompl</exec_depend>
      <exec_depend>moveit_planners_stomp</exec_depend>
      <exec_depend>moveit_plugins</exec_depend>
      <exec_depend>effort_controllers</exec_depend>
      <exec_depend>joint_limits</exec_depend>
      <exec_depend>position_controllers</exec_depend>
      <exec_depend>ros2_controllers</exec_depend>
      <exec_depend>velocity_controllers</exec_depend>
      
      <exec_depend>moveit_ros_move_group</exec_depend>
      <exec_depend>moveit_kinematics</exec_depend>
      <exec_depend>moveit_planners</exec_depend>
      <exec_depend>moveit_simple_controller_manager</exec_depend>
      <exec_depend>joint_state_publisher</exec_depend>
      <exec_depend>joint_state_publisher_gui</exec_depend>
      <exec_depend>tf2_ros</exec_depend>
      <exec_depend>xacro</exec_depend>
      <exec_depend>controller_manager</exec_depend>
      <exec_depend>moveit_configs_utils</exec_depend>
      <exec_depend>moveit_ros_visualization</exec_depend>
      <exec_depend>moveit_ros_warehouse</exec_depend>
      <exec_depend>moveit_setup_assistant</exec_depend>
      <exec_depend>robot_state_publisher</exec_depend>
      <exec_depend>rviz2</exec_depend>
      <exec_depend>rviz_common</exec_depend>
      <exec_depend>rviz_default_plugins</exec_depend>

      <exec_depend>gz_ros2_control</exec_depend>
      <exec_depend>launch</exec_depend>
      <exec_depend>ros_gz_bridge</exec_depend>
      <exec_depend>ros_gz_sim</exec_depend>

      <exec_depend>moveit_servo</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
